### ISSUE TITLE
Swift 4.2 support with XCode 10.0

### ISSUE THREAD

**Issue by muthukrishnanOCS** [banjun/WSDL2Swift#6]
Hi @banjun , 
please give support for Swift 4.2 and let me know once its done.
Thanks

**Comment by banjun** [comment]
To be clear, would you write down issues you faced building with Swift 4.2 & Xcode 10, for me and others using WSDL2Swift?
For example...

* WSDL -> Swift generation error
* Build errors when build previously WSDL2Swift-generated codes
* Build warnings when build previously WSDL2Swift-generated codes
* CocoaPods or other integration issues
* Reproducibility in Xcode 9

More specific text input/outputs and/or screenshots are better.


Of course, pull requests for that are welcome. Would you mind to do it?
